version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      DATABASE_HOST : localhost
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: socialwire
    ports:
      - "5432:5432"
    volumes:
      - /postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL : "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"

volumes:
  postgresql-volumes:
    external : true
